// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Stat.proto

package cls.hadarsstatcoprocessor.pb;

public final class Stat {
  private Stat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StatRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes pvID = 1;
    /**
     * <code>required bytes pvID = 1;</code>
     */
    boolean hasPvID();
    /**
     * <code>required bytes pvID = 1;</code>
     */
    com.google.protobuf.ByteString getPvID();

    // required uint32 startTime = 2;
    /**
     * <code>required uint32 startTime = 2;</code>
     */
    boolean hasStartTime();
    /**
     * <code>required uint32 startTime = 2;</code>
     */
    int getStartTime();

    // required uint32 stopTime = 3;
    /**
     * <code>required uint32 stopTime = 3;</code>
     */
    boolean hasStopTime();
    /**
     * <code>required uint32 stopTime = 3;</code>
     */
    int getStopTime();

    // required uint32 pvType = 4;
    /**
     * <code>required uint32 pvType = 4;</code>
     */
    boolean hasPvType();
    /**
     * <code>required uint32 pvType = 4;</code>
     */
    int getPvType();

    // required uint32 scanAdditionTime = 5;
    /**
     * <code>required uint32 scanAdditionTime = 5;</code>
     */
    boolean hasScanAdditionTime();
    /**
     * <code>required uint32 scanAdditionTime = 5;</code>
     */
    int getScanAdditionTime();
  }
  /**
   * Protobuf type {@code hbase.pb.StatRequest}
   */
  public static final class StatRequest extends
      com.google.protobuf.GeneratedMessage
      implements StatRequestOrBuilder {
    // Use StatRequest.newBuilder() to construct.
    private StatRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StatRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StatRequest defaultInstance;
    public static StatRequest getDefaultInstance() {
      return defaultInstance;
    }

    public StatRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StatRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              pvID_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              startTime_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              stopTime_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              pvType_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              scanAdditionTime_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_hbase_pb_StatRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_hbase_pb_StatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cls.hadarsstatcoprocessor.pb.Stat.StatRequest.class, cls.hadarsstatcoprocessor.pb.Stat.StatRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<StatRequest> PARSER =
        new com.google.protobuf.AbstractParser<StatRequest>() {
      public StatRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StatRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StatRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes pvID = 1;
    public static final int PVID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString pvID_;
    /**
     * <code>required bytes pvID = 1;</code>
     */
    public boolean hasPvID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes pvID = 1;</code>
     */
    public com.google.protobuf.ByteString getPvID() {
      return pvID_;
    }

    // required uint32 startTime = 2;
    public static final int STARTTIME_FIELD_NUMBER = 2;
    private int startTime_;
    /**
     * <code>required uint32 startTime = 2;</code>
     */
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 startTime = 2;</code>
     */
    public int getStartTime() {
      return startTime_;
    }

    // required uint32 stopTime = 3;
    public static final int STOPTIME_FIELD_NUMBER = 3;
    private int stopTime_;
    /**
     * <code>required uint32 stopTime = 3;</code>
     */
    public boolean hasStopTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 stopTime = 3;</code>
     */
    public int getStopTime() {
      return stopTime_;
    }

    // required uint32 pvType = 4;
    public static final int PVTYPE_FIELD_NUMBER = 4;
    private int pvType_;
    /**
     * <code>required uint32 pvType = 4;</code>
     */
    public boolean hasPvType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 pvType = 4;</code>
     */
    public int getPvType() {
      return pvType_;
    }

    // required uint32 scanAdditionTime = 5;
    public static final int SCANADDITIONTIME_FIELD_NUMBER = 5;
    private int scanAdditionTime_;
    /**
     * <code>required uint32 scanAdditionTime = 5;</code>
     */
    public boolean hasScanAdditionTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 scanAdditionTime = 5;</code>
     */
    public int getScanAdditionTime() {
      return scanAdditionTime_;
    }

    private void initFields() {
      pvID_ = com.google.protobuf.ByteString.EMPTY;
      startTime_ = 0;
      stopTime_ = 0;
      pvType_ = 0;
      scanAdditionTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPvID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStopTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPvType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScanAdditionTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, pvID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, startTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, stopTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, pvType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, scanAdditionTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, pvID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, startTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, stopTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, pvType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, scanAdditionTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cls.hadarsstatcoprocessor.pb.Stat.StatRequest)) {
        return super.equals(obj);
      }
      cls.hadarsstatcoprocessor.pb.Stat.StatRequest other = (cls.hadarsstatcoprocessor.pb.Stat.StatRequest) obj;

      boolean result = true;
      result = result && (hasPvID() == other.hasPvID());
      if (hasPvID()) {
        result = result && getPvID()
            .equals(other.getPvID());
      }
      result = result && (hasStartTime() == other.hasStartTime());
      if (hasStartTime()) {
        result = result && (getStartTime()
            == other.getStartTime());
      }
      result = result && (hasStopTime() == other.hasStopTime());
      if (hasStopTime()) {
        result = result && (getStopTime()
            == other.getStopTime());
      }
      result = result && (hasPvType() == other.hasPvType());
      if (hasPvType()) {
        result = result && (getPvType()
            == other.getPvType());
      }
      result = result && (hasScanAdditionTime() == other.hasScanAdditionTime());
      if (hasScanAdditionTime()) {
        result = result && (getScanAdditionTime()
            == other.getScanAdditionTime());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPvID()) {
        hash = (37 * hash) + PVID_FIELD_NUMBER;
        hash = (53 * hash) + getPvID().hashCode();
      }
      if (hasStartTime()) {
        hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
        hash = (53 * hash) + getStartTime();
      }
      if (hasStopTime()) {
        hash = (37 * hash) + STOPTIME_FIELD_NUMBER;
        hash = (53 * hash) + getStopTime();
      }
      if (hasPvType()) {
        hash = (37 * hash) + PVTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getPvType();
      }
      if (hasScanAdditionTime()) {
        hash = (37 * hash) + SCANADDITIONTIME_FIELD_NUMBER;
        hash = (53 * hash) + getScanAdditionTime();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cls.hadarsstatcoprocessor.pb.Stat.StatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cls.hadarsstatcoprocessor.pb.Stat.StatRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hbase.pb.StatRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cls.hadarsstatcoprocessor.pb.Stat.StatRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_hbase_pb_StatRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_hbase_pb_StatRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cls.hadarsstatcoprocessor.pb.Stat.StatRequest.class, cls.hadarsstatcoprocessor.pb.Stat.StatRequest.Builder.class);
      }

      // Construct using cls.hadarsstatcoprocessor.pb.Stat.StatRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pvID_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        startTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        stopTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        pvType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        scanAdditionTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_hbase_pb_StatRequest_descriptor;
      }

      public cls.hadarsstatcoprocessor.pb.Stat.StatRequest getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public cls.hadarsstatcoprocessor.pb.Stat.StatRequest build() {
        cls.hadarsstatcoprocessor.pb.Stat.StatRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cls.hadarsstatcoprocessor.pb.Stat.StatRequest buildPartial() {
        cls.hadarsstatcoprocessor.pb.Stat.StatRequest result = new cls.hadarsstatcoprocessor.pb.Stat.StatRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pvID_ = pvID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stopTime_ = stopTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pvType_ = pvType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.scanAdditionTime_ = scanAdditionTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cls.hadarsstatcoprocessor.pb.Stat.StatRequest) {
          return mergeFrom((cls.hadarsstatcoprocessor.pb.Stat.StatRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cls.hadarsstatcoprocessor.pb.Stat.StatRequest other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasPvID()) {
          setPvID(other.getPvID());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasStopTime()) {
          setStopTime(other.getStopTime());
        }
        if (other.hasPvType()) {
          setPvType(other.getPvType());
        }
        if (other.hasScanAdditionTime()) {
          setScanAdditionTime(other.getScanAdditionTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPvID()) {

          return false;
        }
        if (!hasStartTime()) {

          return false;
        }
        if (!hasStopTime()) {

          return false;
        }
        if (!hasPvType()) {

          return false;
        }
        if (!hasScanAdditionTime()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cls.hadarsstatcoprocessor.pb.Stat.StatRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cls.hadarsstatcoprocessor.pb.Stat.StatRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes pvID = 1;
      private com.google.protobuf.ByteString pvID_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes pvID = 1;</code>
       */
      public boolean hasPvID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes pvID = 1;</code>
       */
      public com.google.protobuf.ByteString getPvID() {
        return pvID_;
      }
      /**
       * <code>required bytes pvID = 1;</code>
       */
      public Builder setPvID(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pvID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes pvID = 1;</code>
       */
      public Builder clearPvID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pvID_ = getDefaultInstance().getPvID();
        onChanged();
        return this;
      }

      // required uint32 startTime = 2;
      private int startTime_ ;
      /**
       * <code>required uint32 startTime = 2;</code>
       */
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 startTime = 2;</code>
       */
      public int getStartTime() {
        return startTime_;
      }
      /**
       * <code>required uint32 startTime = 2;</code>
       */
      public Builder setStartTime(int value) {
        bitField0_ |= 0x00000002;
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 startTime = 2;</code>
       */
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startTime_ = 0;
        onChanged();
        return this;
      }

      // required uint32 stopTime = 3;
      private int stopTime_ ;
      /**
       * <code>required uint32 stopTime = 3;</code>
       */
      public boolean hasStopTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 stopTime = 3;</code>
       */
      public int getStopTime() {
        return stopTime_;
      }
      /**
       * <code>required uint32 stopTime = 3;</code>
       */
      public Builder setStopTime(int value) {
        bitField0_ |= 0x00000004;
        stopTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 stopTime = 3;</code>
       */
      public Builder clearStopTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stopTime_ = 0;
        onChanged();
        return this;
      }

      // required uint32 pvType = 4;
      private int pvType_ ;
      /**
       * <code>required uint32 pvType = 4;</code>
       */
      public boolean hasPvType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 pvType = 4;</code>
       */
      public int getPvType() {
        return pvType_;
      }
      /**
       * <code>required uint32 pvType = 4;</code>
       */
      public Builder setPvType(int value) {
        bitField0_ |= 0x00000008;
        pvType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 pvType = 4;</code>
       */
      public Builder clearPvType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pvType_ = 0;
        onChanged();
        return this;
      }

      // required uint32 scanAdditionTime = 5;
      private int scanAdditionTime_ ;
      /**
       * <code>required uint32 scanAdditionTime = 5;</code>
       */
      public boolean hasScanAdditionTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 scanAdditionTime = 5;</code>
       */
      public int getScanAdditionTime() {
        return scanAdditionTime_;
      }
      /**
       * <code>required uint32 scanAdditionTime = 5;</code>
       */
      public Builder setScanAdditionTime(int value) {
        bitField0_ |= 0x00000010;
        scanAdditionTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 scanAdditionTime = 5;</code>
       */
      public Builder clearScanAdditionTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        scanAdditionTime_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hbase.pb.StatRequest)
    }

    static {
      defaultInstance = new StatRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hbase.pb.StatRequest)
  }

  public interface StatResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 count = 1;
    /**
     * <code>required int64 count = 1;</code>
     */
    boolean hasCount();
    /**
     * <code>required int64 count = 1;</code>
     */
    long getCount();

    // required double sum = 2;
    /**
     * <code>required double sum = 2;</code>
     */
    boolean hasSum();
    /**
     * <code>required double sum = 2;</code>
     */
    double getSum();

    // required double squareSum = 3;
    /**
     * <code>required double squareSum = 3;</code>
     */
    boolean hasSquareSum();
    /**
     * <code>required double squareSum = 3;</code>
     */
    double getSquareSum();

    // required double max = 4;
    /**
     * <code>required double max = 4;</code>
     */
    boolean hasMax();
    /**
     * <code>required double max = 4;</code>
     */
    double getMax();

    // required double min = 5;
    /**
     * <code>required double min = 5;</code>
     */
    boolean hasMin();
    /**
     * <code>required double min = 5;</code>
     */
    double getMin();

    // required bool success = 6;
    /**
     * <code>required bool success = 6;</code>
     */
    boolean hasSuccess();
    /**
     * <code>required bool success = 6;</code>
     */
    boolean getSuccess();

    // optional string error = 7;
    /**
     * <code>optional string error = 7;</code>
     */
    boolean hasError();
    /**
     * <code>optional string error = 7;</code>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 7;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code hbase.pb.StatResponse}
   */
  public static final class StatResponse extends
      com.google.protobuf.GeneratedMessage
      implements StatResponseOrBuilder {
    // Use StatResponse.newBuilder() to construct.
    private StatResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StatResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StatResponse defaultInstance;
    public static StatResponse getDefaultInstance() {
      return defaultInstance;
    }

    public StatResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StatResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              count_ = input.readInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              sum_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              squareSum_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              max_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              min_ = input.readDouble();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              success_ = input.readBool();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              error_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_hbase_pb_StatResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_hbase_pb_StatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cls.hadarsstatcoprocessor.pb.Stat.StatResponse.class, cls.hadarsstatcoprocessor.pb.Stat.StatResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<StatResponse> PARSER =
        new com.google.protobuf.AbstractParser<StatResponse>() {
      public StatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StatResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StatResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 count = 1;
    public static final int COUNT_FIELD_NUMBER = 1;
    private long count_;
    /**
     * <code>required int64 count = 1;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 count = 1;</code>
     */
    public long getCount() {
      return count_;
    }

    // required double sum = 2;
    public static final int SUM_FIELD_NUMBER = 2;
    private double sum_;
    /**
     * <code>required double sum = 2;</code>
     */
    public boolean hasSum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double sum = 2;</code>
     */
    public double getSum() {
      return sum_;
    }

    // required double squareSum = 3;
    public static final int SQUARESUM_FIELD_NUMBER = 3;
    private double squareSum_;
    /**
     * <code>required double squareSum = 3;</code>
     */
    public boolean hasSquareSum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double squareSum = 3;</code>
     */
    public double getSquareSum() {
      return squareSum_;
    }

    // required double max = 4;
    public static final int MAX_FIELD_NUMBER = 4;
    private double max_;
    /**
     * <code>required double max = 4;</code>
     */
    public boolean hasMax() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double max = 4;</code>
     */
    public double getMax() {
      return max_;
    }

    // required double min = 5;
    public static final int MIN_FIELD_NUMBER = 5;
    private double min_;
    /**
     * <code>required double min = 5;</code>
     */
    public boolean hasMin() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required double min = 5;</code>
     */
    public double getMin() {
      return min_;
    }

    // required bool success = 6;
    public static final int SUCCESS_FIELD_NUMBER = 6;
    private boolean success_;
    /**
     * <code>required bool success = 6;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bool success = 6;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    // optional string error = 7;
    public static final int ERROR_FIELD_NUMBER = 7;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 7;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string error = 7;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 7;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      count_ = 0L;
      sum_ = 0D;
      squareSum_ = 0D;
      max_ = 0D;
      min_ = 0D;
      success_ = false;
      error_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSquareSum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, count_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, sum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, squareSum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, max_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, min_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, success_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getErrorBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, count_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, sum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, squareSum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, max_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, min_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, success_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getErrorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cls.hadarsstatcoprocessor.pb.Stat.StatResponse)) {
        return super.equals(obj);
      }
      cls.hadarsstatcoprocessor.pb.Stat.StatResponse other = (cls.hadarsstatcoprocessor.pb.Stat.StatResponse) obj;

      boolean result = true;
      result = result && (hasCount() == other.hasCount());
      if (hasCount()) {
        result = result && (getCount()
            == other.getCount());
      }
      result = result && (hasSum() == other.hasSum());
      if (hasSum()) {
        result = result && (Double.doubleToLongBits(getSum())    == Double.doubleToLongBits(other.getSum()));
      }
      result = result && (hasSquareSum() == other.hasSquareSum());
      if (hasSquareSum()) {
        result = result && (Double.doubleToLongBits(getSquareSum())    == Double.doubleToLongBits(other.getSquareSum()));
      }
      result = result && (hasMax() == other.hasMax());
      if (hasMax()) {
        result = result && (Double.doubleToLongBits(getMax())    == Double.doubleToLongBits(other.getMax()));
      }
      result = result && (hasMin() == other.hasMin());
      if (hasMin()) {
        result = result && (Double.doubleToLongBits(getMin())    == Double.doubleToLongBits(other.getMin()));
      }
      result = result && (hasSuccess() == other.hasSuccess());
      if (hasSuccess()) {
        result = result && (getSuccess()
            == other.getSuccess());
      }
      result = result && (hasError() == other.hasError());
      if (hasError()) {
        result = result && getError()
            .equals(other.getError());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCount()) {
        hash = (37 * hash) + COUNT_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getCount());
      }
      if (hasSum()) {
        hash = (37 * hash) + SUM_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getSum()));
      }
      if (hasSquareSum()) {
        hash = (37 * hash) + SQUARESUM_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getSquareSum()));
      }
      if (hasMax()) {
        hash = (37 * hash) + MAX_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getMax()));
      }
      if (hasMin()) {
        hash = (37 * hash) + MIN_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(
            Double.doubleToLongBits(getMin()));
      }
      if (hasSuccess()) {
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + hashBoolean(getSuccess());
      }
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cls.hadarsstatcoprocessor.pb.Stat.StatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cls.hadarsstatcoprocessor.pb.Stat.StatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cls.hadarsstatcoprocessor.pb.Stat.StatResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hbase.pb.StatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cls.hadarsstatcoprocessor.pb.Stat.StatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_hbase_pb_StatResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_hbase_pb_StatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cls.hadarsstatcoprocessor.pb.Stat.StatResponse.class, cls.hadarsstatcoprocessor.pb.Stat.StatResponse.Builder.class);
      }

      // Construct using cls.hadarsstatcoprocessor.pb.Stat.StatResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        count_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        sum_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        squareSum_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        max_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        min_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_hbase_pb_StatResponse_descriptor;
      }

      public cls.hadarsstatcoprocessor.pb.Stat.StatResponse getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      public cls.hadarsstatcoprocessor.pb.Stat.StatResponse build() {
        cls.hadarsstatcoprocessor.pb.Stat.StatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cls.hadarsstatcoprocessor.pb.Stat.StatResponse buildPartial() {
        cls.hadarsstatcoprocessor.pb.Stat.StatResponse result = new cls.hadarsstatcoprocessor.pb.Stat.StatResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sum_ = sum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.squareSum_ = squareSum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.max_ = max_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.min_ = min_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.success_ = success_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cls.hadarsstatcoprocessor.pb.Stat.StatResponse) {
          return mergeFrom((cls.hadarsstatcoprocessor.pb.Stat.StatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cls.hadarsstatcoprocessor.pb.Stat.StatResponse other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasSum()) {
          setSum(other.getSum());
        }
        if (other.hasSquareSum()) {
          setSquareSum(other.getSquareSum());
        }
        if (other.hasMax()) {
          setMax(other.getMax());
        }
        if (other.hasMin()) {
          setMin(other.getMin());
        }
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        if (other.hasError()) {
          bitField0_ |= 0x00000040;
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCount()) {

          return false;
        }
        if (!hasSum()) {

          return false;
        }
        if (!hasSquareSum()) {

          return false;
        }
        if (!hasMax()) {

          return false;
        }
        if (!hasMin()) {

          return false;
        }
        if (!hasSuccess()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cls.hadarsstatcoprocessor.pb.Stat.StatResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cls.hadarsstatcoprocessor.pb.Stat.StatResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 count = 1;
      private long count_ ;
      /**
       * <code>required int64 count = 1;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 count = 1;</code>
       */
      public long getCount() {
        return count_;
      }
      /**
       * <code>required int64 count = 1;</code>
       */
      public Builder setCount(long value) {
        bitField0_ |= 0x00000001;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 count = 1;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0L;
        onChanged();
        return this;
      }

      // required double sum = 2;
      private double sum_ ;
      /**
       * <code>required double sum = 2;</code>
       */
      public boolean hasSum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double sum = 2;</code>
       */
      public double getSum() {
        return sum_;
      }
      /**
       * <code>required double sum = 2;</code>
       */
      public Builder setSum(double value) {
        bitField0_ |= 0x00000002;
        sum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double sum = 2;</code>
       */
      public Builder clearSum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sum_ = 0D;
        onChanged();
        return this;
      }

      // required double squareSum = 3;
      private double squareSum_ ;
      /**
       * <code>required double squareSum = 3;</code>
       */
      public boolean hasSquareSum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double squareSum = 3;</code>
       */
      public double getSquareSum() {
        return squareSum_;
      }
      /**
       * <code>required double squareSum = 3;</code>
       */
      public Builder setSquareSum(double value) {
        bitField0_ |= 0x00000004;
        squareSum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double squareSum = 3;</code>
       */
      public Builder clearSquareSum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        squareSum_ = 0D;
        onChanged();
        return this;
      }

      // required double max = 4;
      private double max_ ;
      /**
       * <code>required double max = 4;</code>
       */
      public boolean hasMax() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double max = 4;</code>
       */
      public double getMax() {
        return max_;
      }
      /**
       * <code>required double max = 4;</code>
       */
      public Builder setMax(double value) {
        bitField0_ |= 0x00000008;
        max_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double max = 4;</code>
       */
      public Builder clearMax() {
        bitField0_ = (bitField0_ & ~0x00000008);
        max_ = 0D;
        onChanged();
        return this;
      }

      // required double min = 5;
      private double min_ ;
      /**
       * <code>required double min = 5;</code>
       */
      public boolean hasMin() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required double min = 5;</code>
       */
      public double getMin() {
        return min_;
      }
      /**
       * <code>required double min = 5;</code>
       */
      public Builder setMin(double value) {
        bitField0_ |= 0x00000010;
        min_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double min = 5;</code>
       */
      public Builder clearMin() {
        bitField0_ = (bitField0_ & ~0x00000010);
        min_ = 0D;
        onChanged();
        return this;
      }

      // required bool success = 6;
      private boolean success_ ;
      /**
       * <code>required bool success = 6;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bool success = 6;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>required bool success = 6;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000020;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool success = 6;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000020);
        success_ = false;
        onChanged();
        return this;
      }

      // optional string error = 7;
      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 7;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string error = 7;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 7;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 7;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 7;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000040);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 7;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        error_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hbase.pb.StatResponse)
    }

    static {
      defaultInstance = new StatResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hbase.pb.StatResponse)
  }

  /**
   * Protobuf service {@code hbase.pb.StatService}
   */
  public static abstract class StatService
      implements com.google.protobuf.Service {
    protected StatService() {}

    public interface Interface {
      /**
       * <code>rpc getStat(.hbase.pb.StatRequest) returns (.hbase.pb.StatResponse);</code>
       */
      public abstract void getStat(
              com.google.protobuf.RpcController controller,
              cls.hadarsstatcoprocessor.pb.Stat.StatRequest request,
              com.google.protobuf.RpcCallback<cls.hadarsstatcoprocessor.pb.Stat.StatResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new StatService() {
        @java.lang.Override
        public  void getStat(
            com.google.protobuf.RpcController controller,
            cls.hadarsstatcoprocessor.pb.Stat.StatRequest request,
            com.google.protobuf.RpcCallback<cls.hadarsstatcoprocessor.pb.Stat.StatResponse> done) {
          impl.getStat(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getStat(controller, (cls.hadarsstatcoprocessor.pb.Stat.StatRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return cls.hadarsstatcoprocessor.pb.Stat.StatRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return cls.hadarsstatcoprocessor.pb.Stat.StatResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getStat(.hbase.pb.StatRequest) returns (.hbase.pb.StatResponse);</code>
     */
    public abstract void getStat(
        com.google.protobuf.RpcController controller,
        cls.hadarsstatcoprocessor.pb.Stat.StatRequest request,
        com.google.protobuf.RpcCallback<cls.hadarsstatcoprocessor.pb.Stat.StatResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return cls.hadarsstatcoprocessor.pb.Stat.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getStat(controller, (cls.hadarsstatcoprocessor.pb.Stat.StatRequest)request,
            com.google.protobuf.RpcUtil.<cls.hadarsstatcoprocessor.pb.Stat.StatResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return cls.hadarsstatcoprocessor.pb.Stat.StatRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return cls.hadarsstatcoprocessor.pb.Stat.StatResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends cls.hadarsstatcoprocessor.pb.Stat.StatService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getStat(
          com.google.protobuf.RpcController controller,
          cls.hadarsstatcoprocessor.pb.Stat.StatRequest request,
          com.google.protobuf.RpcCallback<cls.hadarsstatcoprocessor.pb.Stat.StatResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          cls.hadarsstatcoprocessor.pb.Stat.StatResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            cls.hadarsstatcoprocessor.pb.Stat.StatResponse.class,
            cls.hadarsstatcoprocessor.pb.Stat.StatResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public cls.hadarsstatcoprocessor.pb.Stat.StatResponse getStat(
              com.google.protobuf.RpcController controller,
              cls.hadarsstatcoprocessor.pb.Stat.StatRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public cls.hadarsstatcoprocessor.pb.Stat.StatResponse getStat(
          com.google.protobuf.RpcController controller,
          cls.hadarsstatcoprocessor.pb.Stat.StatRequest request)
          throws com.google.protobuf.ServiceException {
        return (cls.hadarsstatcoprocessor.pb.Stat.StatResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          cls.hadarsstatcoprocessor.pb.Stat.StatResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:hbase.pb.StatService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hbase_pb_StatRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hbase_pb_StatRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hbase_pb_StatResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hbase_pb_StatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nStat.proto\022\010hbase.pb\"j\n\013StatRequest\022\014\n" +
      "\004pvID\030\001 \002(\014\022\021\n\tstartTime\030\002 \002(\r\022\020\n\010stopTi" +
      "me\030\003 \002(\r\022\016\n\006pvType\030\004 \002(\r\022\030\n\020scanAddition" +
      "Time\030\005 \002(\r\"w\n\014StatResponse\022\r\n\005count\030\001 \002(" +
      "\003\022\013\n\003sum\030\002 \002(\001\022\021\n\tsquareSum\030\003 \002(\001\022\013\n\003max" +
      "\030\004 \002(\001\022\013\n\003min\030\005 \002(\001\022\017\n\007success\030\006 \002(\010\022\r\n\005" +
      "error\030\007 \001(\t2G\n\013StatService\0228\n\007getStat\022\025." +
      "hbase.pb.StatRequest\032\026.hbase.pb.StatResp" +
      "onseB,\n\034cls.hadarsstatcoprocessor.pbB\004St" +
      "atH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hbase_pb_StatRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hbase_pb_StatRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hbase_pb_StatRequest_descriptor,
              new java.lang.String[] { "PvID", "StartTime", "StopTime", "PvType", "ScanAdditionTime", });
          internal_static_hbase_pb_StatResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_hbase_pb_StatResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hbase_pb_StatResponse_descriptor,
              new java.lang.String[] { "Count", "Sum", "SquareSum", "Max", "Min", "Success", "Error", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
